version: '3.1'
services:
  angular6container:
    container_name: angularapp
    hostname: angularapp
    image: angular6
    restart: always
    ports:
      - 4200:4200
    volumes:
      - /home/compiler/angularapp_vol:/app
#volumes:
     #angularapp_vol:

